" Turn off vi mode, we are using VIM!
set nocompatible

" Turn on pathogen, our plugin package manager.
call pathogen#infect()
" Run helptags to load docs from all the bundles.
Helptags

" Turn on syntax highlighting.
syntax on

" Change to the correct indention and plugins dependent on the file type.
filetype on
filetype indent on
filetype plugin on

" Turn on line numbers.
set number

" Turn on the visual bell.
set visualbell
set noerrorbells

" Tab Settings
set autoindent
set smartindent
set smarttab
set expandtab

set shiftwidth=2
set softtabstop=2
set tabstop=2

" Allow for cursor beyond last character.
set virtualedit=onemore

" Store more history!
set history=1000

" Configure wildignore
set wildignore+=*.gz,*.swp,*.bak,*.pyc,*.class
" Don't load test records if they are in a project.
set wildignore+=*/test-records/*

" smart case-sensitive searching
set ignorecase
set smartcase

" remap ESC
inoremap jj <ESC>

" a few emacs keybindings while in insert mode
inoremap <C-a> <Home>
inoremap <C-e> <End>
inoremap <C-f> <Right>
inoremap <C-b> <Left>
inoremap <C-p> <Up>
inoremap <C-n> <Down>

" Wrapped lines go to next row not next line in file
noremap j gj
noremap k gk

" Remap the leader key
let mapleader=','
"
" Strip all trailing whitespace in the current file
nnoremap <leader>W :%s/\s\+$//<CR>:let @/=''<CR>

" Indent the whole file and return to the current line
nnoremap <leader>i gg=G''

" Run Ack
nnoremap <leader>a :Ack

" Generate ctags
nnoremap <silent> <leader>t :silent !ctags -R .<CR><C-l>

" CtrlP shortcuts
nnoremap <silent> <leader>p :CtrlP<CR>
nnoremap <silent> <leader>P :CtrlPTag<CR>

" Quickly edit/reload the vimrc file
nmap <silent> <leader>ev :vsplit<CR><C-w><C-w>:e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" Shortcuts for opening new split windows
nmap <silent> <leader>h :split<CR><C-w><C-w>
nmap <silent> <leader>v :vsplit<CR><C-w><C-w>
nmap <silent> <leader>q :q<CR>

" Shortcut to reloading last buffer
nmap <silent> <leader>b :b#<CR>

" Map Y to yank until EOL
map Y y$

" Tired of hitting F1 accidentally?
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

" Toggle highlighting the current line and column.
nnoremap <silent> <F10> :set cursorline!<CR>:set cursorcolumn!<CR>

" F11 to toggle between 'paste' and 'nopaste' in insert mode
set pastetoggle=<F11>

" F12 to toggle line numbers and git-gutter
nnoremap <silent> <F12> :set nonumber!<CR>:GitGutterToggle<CR>

" NERDTree Settings
let NERDTreeMinimalUI  = 1
let NERDTreeDirArrows  = 0
let g:NERDTreeWinSize  = 30
let NERDTreeQuitOnOpen = 1
map <silent> <C-n> :NERDTreeToggle<CR>

" CtrlP Settings
let g:ctrlp_custom_ignore = 'tags'

" Configure how vim looks.
colorscheme jellybeans

" Make the GUI nice.
if has('gui_running')
  " Turn off the menu, tool, and scroll bar.
  set guioptions-=m
  set guioptions-=T
  set guioptions-=L
  set guioptions-=l
  set guioptions-=r
  set guioptions-=R

  " Increase the starting size of the editor.
  set lines=40
  set columns=100

  " Make NERDTree look nice when using a GUI.
  let NERDTreeDirArrows = 1

  " Default to line and column highlighting.
  set cursorline cursorcolumn

  " Set up some decent fonts.
  if has("gui_win32")
    set guifont=Consolas:h10:cANSI
  elseif has("gui_mac")
    set guifont=Menlo\ Regular:h15
  endif
endif
