" Turn on pathogen.
call pathogen#infect()

" Setup some sane defaults for vim.
set nocompatible      " We're running Vim, not Vi!
syntax on             " Enable syntax highlighting
filetype on           " Enable filetype detection
filetype indent on    " Enable filetype-specific indenting
filetype plugin on    " Enable filetype-specific pluginsyntax enable

" Tab Settings
set expandtab
set tabstop=2 shiftwidth=2 softtabstop=2
set autoindent
