" Turn off vi mode, we are using VIM!
set nocompatible

" Turn on pathogen, our plugin package manager.
call pathogen#infect()
" Run helptags to load docs from all the bundles.
Helptags

" Turn on syntax highlighting.
syntax on

" Change to the correct indention and plugins dependent on the file type.
filetype on
filetype indent on
filetype plugin on

" Turn on line numbers.
set number

" Turn on the visual bell.
set visualbell
set noerrorbells

" Tab Settings
set autoindent
set smartindent
set smarttab
set expandtab

set shiftwidth=2
set softtabstop=2
set tabstop=2

" Allow for cursor beyond last character.
set virtualedit=onemore

" Store more history!
set history=1000

" Configure wildignore
set wildignore+=*.gz,*.swp,*.bak,*.pyc,*.class
" Don't load test records if they are in a project.
set wildignore+=*/test-records/*

" smart case-sensitive searching
set ignorecase
set smartcase

" Configure how vim looks.
set cursorline
colorscheme jellybeans

" remap the leader key
let mapleader=','

" remap ESC
inoremap jj <ESC>

" a few emacs keybindings while in insert mode
inoremap <C-a> <Home>
inoremap <C-e> <End>
inoremap <C-f> <Right>
inoremap <C-b> <Left>
inoremap <C-p> <Up>
inoremap <C-n> <Down>

" tired of hitting F1 accidentally?
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

" strip all trailing whitespace in the current file
nnoremap <leader>W :%s/\s\+$//<CR>:let @/=''<CR>

" indent the whole file and return to the current line
nnoremap <leader>i gg=G''

" a shortcut to Ack
nnoremap <leader>a :Ack

" quickly edit/reload the vimrc file
nmap <silent> <leader>ev :vsplit<CR><C-w><C-w>:e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" shortcuts for opening new split windows
nmap <silent> <leader>h :split<CR><C-w><C-w>
nmap <silent> <leader>v :vsplit<CR><C-w><C-w>
nmap <silent> <leader>q :q<CR>

" F11 to toggle between 'paste' and 'nopaste'
set pastetoggle=<F11>

" Map Y to yank until EOL
map Y y$

" NERDTree Settings
let NERDTreeMinimalUI  = 1
let NERDTreeDirArrows  = 0
let g:NERDTreeWinSize  = 30
let NERDTreeQuitOnOpen = 1
map <C-n> :NERDTreeToggle<CR>

" Make the GUI nice.
if has('gui_running')
  " Turn off the menu, tool, and scroll bar.
  set guioptions-=m
  set guioptions-=T
  set guioptions-=L
  set guioptions-=l
  set guioptions-=r
  set guioptions-=R

  " Increase the starting size of the editor.
  set lines=40
  set columns=100

  " Make NERDTree look nice when using a GUI.
  let NERDTreeDirArrows = 1

  " Set up some decent fonts.
  if has("gui_win32")
    set guifont=Consolas:h10:cANSI
  elseif has("gui_macvim")
    set guifont=Menlo\ Regular:h15
  endif
endif
